name: 'Liberty AI PR Review'
description: 'Docker-based AI code review using LLM'
author: 'Andrei Andreev'
branding:
  icon: 'code'
  color: 'green'

inputs:
  github_token:
    description: 'GitHub token'
    required: true

  debug:
    description: 'Debug mode'
    required: false
    default: 'false'

  add_review_resolution:
    description: 'Add review resolution (like "APPROVE", "REQUEST_CHANGES", "COMMENT") to the PR'
    required: false
    default: 'false'

  add_joke:
    description: 'Add a joke to the review comment'
    required: false
    default: 'false'

  author_customization:
    description: 'YAML configuration for customizing reviews based on PR author'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.github_token }}"
    - "${{ inputs.debug }}"
    - "${{ inputs.add_review_resolution }}"
    - "${{ inputs.add_joke }}"
    - "${{ inputs.author_customization }}"
