[pytest]

addopts = --verbose --durations=3

# asyncio
;asyncio_mode = auto
;asyncio_default_fixture_loop_scope = function

# for logs output

# set to `true` when needed for debugging purposes.
log_cli = false
log_cli_level = DEBUG
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)d)
log_cli_date_format = %Y-%m-%d %H:%M:%S
