import argparse
import os
from pathlib import Path
from unittest import mock
from unittest.mock import Mock, patch

from jinja2 import Environment

from ai_review.review import extract_json, get_author_specific_prompt_additions, parse_author_customization, \
    process_review


@patch.object(Path, 'read_text', Mock(return_value='prompt'))
@patch.object(Environment, 'get_template', Mock(return_value=Mock(render=Mock(return_value='user_prompt'))))
@patch('litellm.completion')
def test_process_review(mock_completion):
    """ Test the process_review function """
    diff_content = "Sample diff content"
    args = argparse.Namespace(
        github_token='gh_token',
        debug='false',
        add_review_resolution='false',
        add_joke='true',
        author_customization='',
    )

    expected_response = 'Review content generated by LLM.'

    mock_response = mock.Mock()
    mock_response.choices = [mock.Mock(message=mock.Mock(content=expected_response))]
    mock_completion.return_value = mock_response

    with patch.dict(os.environ, {'LLM_MODEL': 'gpt-4o'}):
        result = process_review('title', 'body', diff_content, 'test_author', args, False)

    assert result == expected_response

    mock_completion.assert_called_once()
    call_kwargs = mock_completion.call_args[1]

    assert call_kwargs['model'] == 'gpt-4o'
    assert call_kwargs['messages'] == [
        {"role": 'system', "content": "prompt\nprompt"},
        {'role': 'user', 'content': 'user_prompt'}
    ]

    assert 'api_key' not in call_kwargs
    assert 'base_url' not in call_kwargs
    assert 'api_version' not in call_kwargs


def test_extract_json():
    text = '''
    any
    {
    json {
    }
    }
    text
    '''

    expected = '''{
    json {
    }
    }'''

    assert extract_json(text) == expected


def test_extract_no_text():
    assert not extract_json(None)
    assert extract_json('') == ''


def test_parse_author_customization_empty():
    """ Test parsing empty author customization """
    assert parse_author_customization('') == {}
    assert parse_author_customization(None) == {}
    assert parse_author_customization('   ') == {}


def test_parse_author_customization_valid_yaml():
    """ Test parsing valid YAML author customization """
    yaml_config = """
torvalds: "Be extra careful with this user's code"
defunkt: "Quick review for this user"
"""
    result = parse_author_customization(yaml_config)
    expected = {
        'torvalds': "Be extra careful with this user's code",
        'defunkt': "Quick review for this user"
    }
    assert result == expected


def test_parse_author_customization_invalid_yaml():
    """ Test parsing invalid YAML returns empty dict """
    invalid_yaml = "invalid: yaml: content: ["
    result = parse_author_customization(invalid_yaml)
    assert result == {}


def test_get_author_specific_prompt_additions_direct_match():
    """ Test getting prompt additions for direct author match """
    customizations = {
        'torvalds': "Be extra careful",
        'defunkt': "Quick review"
    }
    result = get_author_specific_prompt_additions('torvalds', customizations)
    assert result == "Be extra careful"

    result = get_author_specific_prompt_additions('defunkt', customizations)
    assert result == "Quick review"


def test_get_author_specific_prompt_additions_no_match():
    """ Test getting prompt additions with no match - returns empty string """
    customizations = {
        'torvalds': "Be extra careful"
    }
    result = get_author_specific_prompt_additions('unknown_user', customizations)
    assert result == ""


def test_get_author_specific_prompt_additions_empty():
    """ Test getting prompt additions with empty inputs """
    assert get_author_specific_prompt_additions('', {}) == ""
    assert get_author_specific_prompt_additions('user', {}) == ""
    assert get_author_specific_prompt_additions('', {'user': 'test'}) == ""
