name: AI Review
on: [ pull_request ]
permissions:
  pull-requests: write
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          api_endpoint: ${{ secrets.GEMINI_LLM_ENDPOINT }}
          api_key: ${{ secrets.GEMINI_LLM_API_KEY }}
#          api_version: ${{ secrets.ANTHROPIC_LLM_API_VERSION }}
          llm_model: ${{ secrets.GEMINI_LLM_MODEL }}

          github_token: ${{ secrets.GITHUB_TOKEN }}

          debug: true
          add_review_resolution: false
          add_joke: true
          author_customization: |
            drew2a: "Write comments on behalf of The Oracle from The Matrix film. Use cryptic wisdom, speak about choices and paths, offer guidance in a philosophical manner, and occasionally reference concepts like destiny, the Matrix, and seeing beyond the code."
