name: Pytest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements-test.txt
      - run: echo "PYTHONPATH=.:$PYTHONPATH" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          pytest \
            --cov \
            --cov-report=xml \
            --cov-report=term-missing

      - name: Compare coverage (optional)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          diff-cover coverage.xml \
            --compare-branch=origin/main \
            --json-report=diff_coverage.json \
            --fail-under=80

      - name: Annotate uncovered lines
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: drew2a/annotate-coverage-action@v1
        with:
          json_path: "diff_coverage.json"
